version: '3'
services:
  php:
    image: php:8.3.1-fpm
    volumes:
      - ./src:/var/www
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      # If you need more than 60 request per hour, consider to setup a token
      # https://github.com/settings/tokens
      - TOKEN=<TOKEN_IF_NEEDED>
      - USERID=<GITHUB_USERNAME>
  nginx:
    image: nginx:1.13.8
    ports:
      - 3008:80
    expose:
      - 3008
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php